### ISSUE TITLE
Why have the `Shake` be a `Component` instead of `Resource`

### ISSUE THREAD

**Issue by PraxTube** [johanhelsing/bevy_trauma_shake#1]
I have a very similar camera shake in my game (also based on the same GDC talk),
though I have am handling the camera shake through a resource instead of a component.
Was just wondering why you chose to use a component, so that you can support
multiple cameras?

**Comment by johanhelsing** [comment]
I was also thinking the same thing yesterday... It sort of just felt that it belonged there. It would work better for split screen games at least, but the point of this crate is also to be ridiculously easy to use. I assume you're asking because you find resources easier to use?

I was also thinking of perhaps optionally adding trauma to all cameras through events or commands.

So either

```rust
fn damage_system(mut trauma_events: EventWriter<TraumaEvent>) {
    trauma_events.send(TraumaEvent::new(0.2));
}
```

or

```rust
fn damage_system(mut commands: Commands) {
    commands.add_trauma(0.2);
}
```

Events would match how I did gamepad rumble events in bevy itself, so perhaps that's the best approach.

**Comment by PraxTube** [comment]
Oh yeah I didn't consider split screen at all! I find it easier to more intuitive with a Resource, yes (but I get why you would use components). Events are a pretty neat way of adding shake to all cameras, though that doesn't work nicely with rollbacks (unless you are fine with taking the risk of not rolling back camera shake). Wait you can define custom commands!? Dude bevy is so sick.

**Comment by johanhelsing** [comment]
Yeah :)

The idea is that this crate should be super-simple to use. It's nice to be flexible, but I'd much rather have a simple and easy to use API. People that need something very specific can just fork.

I think having it as a component is the best approach since it works with rollback, and just provide some convenience events/commands that are entirely optional to use.

Commands could be implemented in a rollback-safe way at least.

**Comment by johanhelsing** [comment]
I added three different approaches, just for fun. See:

https://github.com/johanhelsing/bevy_trauma_shake/blob/main/examples/shakes.rs
https://github.com/johanhelsing/bevy_trauma_shake/blob/main/examples/commands.rs
https://github.com/johanhelsing/bevy_trauma_shake/blob/main/examples/events.rs

**Comment by PraxTube** [comment]
Very nice :+1: 

I totally agree, simplicity > flexibility.
